export const FETCH_TASKS = 'FETCH_TASKS';
export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const EDIT_TASK = 'EDIT_TASK';
export const SAVE_TASKS = 'SAVE_TASKS';
export const REPORT_NOTIFICATION = 'REPORT_NOTIFICATION';
export const RESET_NOTIFICATION = 'RESET_NOTIFICATION';